### ISSUE TITLE
Add UNION ALL and δ 

### ISSUE THREAD

**Issue by RicardoMonteiroSimoes** [dbis-uibk/relax#20]
UNION ALL is basically Union without the elimination of multiple equal values, and small delta eliminates the multiple equal values

**Comment by immutablestate** [comment]
RelaX tries to follow the conventions of classical relational algebra, i.e., we are working with sets. That's why every operator through which duplicates could arise implicitly performs duplicate elimination. 

The δ operator only makes sense on a version of relational algebra which operates on multisets, which is not what RelaX is doing. Consequently, we will not add it.
